version: '3.3'
networks:
  microservice:
    external:
      name: microservice

services: 
  consul-dc1-node1:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc1 --bootstrap-expect=1
  consul-dc1-node2:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    depends_on:
      - consul-dc1-node1
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc1 --join consul-dc1-node1
  consul-dc1-node3:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    depends_on:
      - consul-dc1-node1
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc1 --join consul-dc1-node1
  consul-dc1-node4:
    image: consul
    restart: always
    ports:
     - 8500:8500
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
    depends_on:
      - consul-dc1-node1
    command: agent --server=false --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc1 --join consul-dc1-node4
  consul-dc2-node1:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    depends_on:
      - consul-dc1-node1
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc2 --bootstrap-expect=1
  consul-dc2-node2:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    depends_on:
      - consul-dc2-node1
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc2 --join consul-dc2-node1
  consul-dc2-node3:
    image: consul
    restart: always
    deploy:
      replicas: 1  
      restart_policy:
        condition: any        
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    depends_on:
      - consul-dc2-node1
    command: agent --server=true --client=0.0.0.0 -ui -hcl='acl {enabled=false}' -datacenter=dc2 --join consul-dc2-node1
  registrator:    
    image: gliderlabs/registrator:latest
    restart: always
    volumes: 
     - /var/run/docker.sock:/tmp/docker.sock
    deploy:
      mode: global
    depends_on:
      - consul-dc1-node4
    command: -cleanup -resync=10 --internal consul://consul-dc1-node4:8500